chore: fixed times and scheduling
Signed-off-by: RealAnna <anna.reale@dynatrace.com>

diff --git a/.github/workflows/zero-downtime-tests.yml b/.github/workflows/zero-downtime-tests.yml
--- a/.github/workflows/zero-downtime-tests.yml
+++ b/.github/workflows/zero-downtime-tests.yml
@@ -396,32 +396,6 @@ jobs:
           cat /tmp/json.log 2>&1 | tee /tmp/gotest.log
           teststat -markdown /tmp/json.log | tee /tmp/gotest2.log
 
-      - name: Generate Github Summary
-        if: always()
-        run: |
-           if [[ $GITHUB_EVENT_NAME == 'schedule' ]]; then
-              echo "* Triggered by: Scheduled build" >> $GITHUB_STEP_SUMMARY
-           else
-              echo "* Triggered by: @$GITHUB_ACTOR" >> $GITHUB_STEP_SUMMARY
-           fi
-          
-            echo "* Branch: $BRANCH" >> $GITHUB_STEP_SUMMARY
-            echo "* Version: $VERSION" >> $GITHUB_STEP_SUMMARY
-            echo "* Datetime: $DATETIME" >> $GITHUB_STEP_SUMMARY
-            echo "* Commit: $GIT_SHA" >> $GITHUB_STEP_SUMMARY
-            echo "* Upgraded to: $UPGRADE_HELM_CHART" >> $GITHUB_STEP_SUMMARY
-            echo "" >>$GITHUB_STEP_SUMMARY
-          
-            echo "<details>" > $GITHUB_STEP_SUMMARY
-            cat /tmp/gotest2.log >> $GITHUB_STEP_SUMMARY
-            echo "</details>" > $GITHUB_STEP_SUMMARY
-          
-            if [[ "${{ github.event.inputs.testUI }}" == 'true' ]]; then
-              echo "<details>" > $GITHUB_STEP_SUMMARY
-              cat /tmp/uitest.log >> $GITHUB_STEP_SUMMARY
-              echo "</details>" > $GITHUB_STEP_SUMMARY
-            fi
-
       - name: Format go test log output
         if: always()
         run: |
@@ -431,6 +405,14 @@ jobs:
       - name: Format cypress log output
         if: always() && github.event.inputs.testUI == 'true'
         run: cat /tmp/uitest.log
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: /tmp/json.log   # Path to test results
+          reporter: jest-junit
 
       #######################################################################
       # TEARDOWN
